### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by ncrash** [aseom/alfred-workflows#1]
그간 너무 편하게 잘 써왔고 이 기회에 감사의 인사를 먼저 전합니다.
오늘 갑자기 안되서 로그를 보니 json 파싱을 못하는것 같습니다.
시간이 허락 되시면 문제해결 부탁 드릴께요

```
Starting debug for 'Daum Dictionary'

[2019-05-17 16:00:19][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "./suggest.py", line 30, in <module>
    data = json.loads(urlopen(url).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by ncrash** [comment]
무슨 이유인지 지금은 잘 되네요 -_-;
본 티켓은 종료 하겠습니다.
